//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class LoginPage extends JPanel {
    // Page1
    JLabel jLabel, jLabel2, jLabel3;
    JTextField unameTf, pswdTf;
    JButton loginButton;

    private LoginPage() {
        //construct components
        jLabel = new JLabel("MITE Kart");
        unameTf = new JTextField(5);
        jLabel2 = new JLabel("Username");
        jLabel3 = new JLabel("Password");
        pswdTf = new JTextField(5);
        loginButton = new JButton("Login");

        //adjust size and set layout
        setPreferredSize(new Dimension(353, 288));
        setLayout(null);

        //add components
        add(jLabel);
        add(unameTf);
        add(jLabel2);
        add(jLabel3);
        add(pswdTf);
        add(loginButton);

        //set component bounds (only needed by Absolute Positioning)
        jLabel.setBounds(130, 35, 60, 30);
        unameTf.setBounds(145, 90, 120, 25);
        jLabel2.setBounds(45, 90, 65, 25);
        jLabel3.setBounds(45, 140, 70, 25);
        pswdTf.setBounds(145, 135, 120, 25);
        loginButton.setBounds(120, 200, 100, 25);

        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get Credentials
                String userName = unameTf.getText();
                String password = pswdTf.getText();

                // Check user if already exist ?
                //if(userName.equals("adarsh") && password.equals("123"))
                //    createAccount();
                productsPage();
            }
        });
    }

    private void productsPage() {
        this.setVisible(false);
        productPage.showPage2();
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("M-Kart Rental Makes Easy");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new LoginPage());
        frame.pack();
        frame.setVisible(true);
    }
}
