//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;
import javax.xml.bind.JAXBException;

public class ProductPage extends JPanel {
    private JLabel jcomp1;
    private JButton jcomp2;
    private JList jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JButton jcomp6;
    private JLabel jcomp7;
    private JComboBox jcomp8;
    private JMenuBar jcomp9;

    public ProductPage() throws FileNotFoundException, JAXBException, ClassNotFoundException {
        //construct preComponents
        String[] jProductList = fetchProducts();
        String[] jcomp8Items = {"30 Days", "60 Days", "120 Days", "180 Days"};
        JMenu fileMenu = new JMenu("File");
        JMenuItem printItem = new JMenuItem("Print");
        fileMenu.add(printItem);
        JMenuItem exitItem = new JMenuItem("Exit");
        fileMenu.add(exitItem);
        JMenu helpMenu = new JMenu("Help");
        JMenuItem contentsItem = new JMenuItem("Contents");
        helpMenu.add(contentsItem);
        JMenuItem aboutItem = new JMenuItem("About");
        helpMenu.add(aboutItem);

        //construct components
        jcomp1 = new JLabel("MITE Kart");
        jcomp2 = new JButton("Rent");
        jcomp3 = new JList(jProductList);
        jcomp4 = new JLabel("Total Balance");
        jcomp5 = new JLabel("0");
        jcomp6 = new JButton("Status");
        jcomp7 = new JLabel("Duration");
        jcomp8 = new JComboBox(jcomp8Items);
        jcomp9 = new JMenuBar();
        jcomp9.add(fileMenu);
        jcomp9.add(helpMenu);

        //adjust size and set layout
        setPreferredSize(new Dimension(353, 288));
        setLayout(null);

        //add components
        add(jcomp1);
        add(jcomp2);
        add(jcomp3);
        add(jcomp4);
        add(jcomp5);
        add(jcomp6);
        add(jcomp7);
        add(jcomp8);
        add(jcomp9);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds(130, 35, 60, 30);
        jcomp2.setBounds(165, 240, 100, 25);
        jcomp3.setBounds(45, 85, 180, 140);
        jcomp4.setBounds(240, 160, 85, 25);
        jcomp5.setBounds(245, 190, 70, 20);
        jcomp6.setBounds(45, 240, 100, 25);
        jcomp7.setBounds(240, 85, 80, 25);
        jcomp8.setBounds(240, 115, 100, 25);
        jcomp9.setBounds(-5, 0, 360, 25);
    }

    static void showPage2() throws FileNotFoundException, JAXBException, ClassNotFoundException {
        JFrame frame = new JFrame("Product Page");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new ProductPage());
        frame.pack();
        frame.setVisible(true);
    }

    String[] fetchProducts() throws FileNotFoundException, JAXBException, ClassNotFoundException {
        Products products = (Products) XMLJavaReadWriters.readFromXML("Products", System.getProperty("user.dir") + "\\src\\product.xml");
        ArrayList<Product> lst = (ArrayList<Product>) products.getProductList();
        String[] productStringList = new String[lst.size()];
        int i = 0;
        for (Product p : lst) {
            productStringList[i] = p.toString();
            i++;
        }
        return productStringList;
    }
}
